### ISSUE TITLE
About gaussian up-sampling

### ISSUE THREAD

**Issue by rishikksh20** [keonlee9420/WaveGrad2#1]
Hi @keonlee9420 , you have mentioned you don't use  Non-Attentive Tacotron's upsampling rather prefer EATS upsampling, is there some specific reason for that ? 
Also what's the inference speed of WaveGrad v2 on cpu ?

**Comment by keonlee9420** [comment]
Hi @rishikksh20 , the model produced NaN value when I introduced the range parameter from predicted duration (as the paper did), so I replaced the learnable range parameter to scalar value as EATS.
I didn't check the speed on CPU, but It took about 1~2 minutes with 1000 iter steps on GPU (12 batches).
