### ISSUE TITLE
colab

### ISSUE THREAD

**Issue by ghost** [keonlee9420/WaveGrad2#2]
Hi, can you please add a google colab for inference?

**Comment by keonlee9420** [comment]
Hi @ak9250 , sorry for the late response. Unfortunately I don't have time to build colab script for now. If you are still interested and willing to construct colab tutorial, any of it is welcome from your contribution.

**Comment by keonlee9420** [comment]
Close the issue due to the inactivity. you can reopen it anytime if you have issues.
