### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by Rongjiehuang** [keonlee9420/WaveGrad2#3]
Hi, nice implementation! I wonder if you could release the pretrained checkpoints, thanks!

**Comment by keonlee9420** [comment]
Hi @Rongjiehuang , sorry for the late answer. I was debugging, and finally I can make the model converge. Now I'm training the model and will release the pre-trained models soon. Please stay tuned!

**Comment by keonlee9420** [comment]
Close the issue due to the inactivity. you can reopen it anytime if you have issues.
