### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by asr2021** [keonlee9420/WaveGrad2#4]
Good job, something wrong with download the pre-trained models. Thanks

**Comment by keonlee9420** [comment]
Hi @asr2021  , sorry for the late answer. I was debugging, and finally I can make the model converge. Now I'm training the model and will release the pre-trained models soon. Please stay tuned!

**Comment by keonlee9420** [comment]
Close the issue due to the inactivity. you can reopen it anytime if you have issues.
